apiVersion: v1
kind: Service
metadata:
    name: wordpress
spec:
    type: NodePort
    ports:
    - port: 80 #puerto que expone
      targetPort: 80 
      nodePort: 3000 # puerto al que apunta dentro del contenedor
    selector:
        role: wordpress # indica que los pods con role == wordpress se les debe enviar el trafico